[package]
name = "jrinx-abi"
authors = [
    "coekjan <cn_yzr@qq.com>"
]
version = "0.1.0"
edition = "2021"
license = "MIT"
description = "ABI for Jrinx"
repository = "https://github.com/Jrinx/Jrinx-abi"
readme = "README.md"

[dependencies]
cfg-if = "1.0.0"
